# Generated by Django 5.1.6 on 2025-02-27 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_calories', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.datetime(2025, 2, 27, 12, 58, 24, 81543))),
                ('end_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('calories_burned', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='workout_image')),
                ('video', models.FileField(blank=True, null=True, upload_to='workout')),
                ('created_at', models.DateField(default=datetime.datetime(2025, 2, 27, 12, 58, 24, 81543))),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_duration', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime(2025, 2, 27, 12, 58, 24, 81543))),
            ],
        ),
    ]
