# Generated by Django 5.1.6 on 2025-02-27 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_mealplan_created_at_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='image',
            new_name='Food_image',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 2, 27, 19, 30, 17, 42516)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 2, 27, 19, 30, 17, 42516)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 2, 27, 19, 30, 17, 42516)),
        ),
    ]
