# Generated by Django 5.1.6 on 2025-03-01 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_image_fooditems_food_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='Food_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 14, 11, 36, 142506)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 14, 11, 36, 142506)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 14, 11, 36, 142506)),
        ),
    ]
