# Generated by Django 5.1.6 on 2025-03-01 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_food_image_fooditems_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 14, 34, 22, 879040)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 14, 34, 22, 879040)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 14, 34, 22, 879040)),
        ),
    ]
