# Generated by Django 5.1.6 on 2025-03-02 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_mealplan_created_at_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 10, 39, 31, 782436)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 10, 39, 31, 782436)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 10, 39, 31, 782436)),
        ),
    ]
