# Generated by Django 5.1.6 on 2025-03-03 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_workout_fitname_alter_mealplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 3, 12, 23, 27, 576656)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 3, 12, 23, 27, 576656)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 3, 12, 23, 27, 577941)),
        ),
    ]
