# Generated by Django 5.1.6 on 2025-03-07 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_mealplan_created_at_alter_workout_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 11, 42, 1, 836214)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 11, 42, 1, 835164)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 11, 42, 1, 836214)),
        ),
    ]
