# Generated by Django 5.1.6 on 2025-03-07 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_mealplan_created_at_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='day',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 13, 26, 54, 538316)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 13, 26, 54, 538316)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 13, 26, 54, 540767)),
        ),
    ]
