# Generated by Django 5.1.6 on 2025-03-07 08:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_mealplan_created_at_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.days'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 13, 36, 3, 449528)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 13, 36, 3, 449528)),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 13, 36, 3, 449528)),
        ),
    ]
