# Generated by Django 5.1.6 on 2025-03-07 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_fooditems_interval_alter_mealplan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='shift',
        ),
        migrations.AddField(
            model_name='interval',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interval',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category image'),
        ),
        migrations.AlterField(
            model_name='days',
            name='choose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 19, 48, 48, 300195)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 7, 19, 48, 48, 298430), null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 19, 48, 48, 300195)),
        ),
    ]
