# Generated by Django 5.1.6 on 2025-03-07 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_mealplan_created_at_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interval',
            old_name='category',
            new_name='shift',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='image',
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 19, 59, 33, 620519)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 7, 19, 59, 33, 620519), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 19, 59, 33, 620519)),
        ),
    ]
