# Generated by Django 5.1.6 on 2025-03-07 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_rename_category_interval_shift_remove_interval_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='Cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='category image'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 21, 32, 1, 783670)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 7, 21, 32, 1, 783670), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 21, 32, 1, 783670)),
        ),
    ]
