# Generated by Django 5.1.6 on 2025-03-08 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_productdb_alter_mealplan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Category_Name',
        ),
        migrations.AddField(
            model_name='productdb',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 18, 33, 54, 674280)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 8, 18, 33, 54, 674280), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 18, 33, 54, 674280)),
        ),
    ]
