# Generated by Django 5.1.6 on 2025-03-08 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_mealplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Category',
            field=models.CharField(blank=True, choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 20, 56, 44, 653562)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 8, 20, 56, 44, 653562), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 20, 56, 44, 655581)),
        ),
    ]
