# Generated by Django 5.1.6 on 2025-03-10 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_productdb_category_alter_mealplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 18, 40, 1, 438130)),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Category',
            field=models.CharField(blank=True, choices=[('Supplements', 'Supplements'), ('Medications', 'Medications')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 10, 18, 40, 1, 437114), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 18, 40, 1, 438130)),
        ),
    ]
