# Generated by Django 5.1.6 on 2025-03-10 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_mealplan_created_at_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 18, 44, 20, 622499)),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Category',
            field=models.CharField(blank=True, choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 10, 18, 44, 20, 622499), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 18, 44, 20, 622499)),
        ),
    ]
