# Generated by Django 5.1.6 on 2025-03-10 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_alter_mealplan_created_at_alter_productdb_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 20, 41, 1, 430709)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 10, 20, 41, 1, 429430), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 20, 41, 1, 430709)),
        ),
    ]
