# Generated by Django 5.1.6 on 2025-04-01 07:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_alter_mealplan_created_at_alter_workout_created_at_and_more'),
        ('fitness', '0011_checkoutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 1, 12, 56, 33, 742843)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 1, 12, 56, 33, 742843), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 1, 12, 56, 33, 742843)),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.signupdb')),
            ],
        ),
    ]
