# Generated by Django 5.1.6 on 2025-04-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_alter_mealplan_created_at_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 1, 18, 52, 7, 678896)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 1, 18, 52, 7, 676882), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 1, 18, 52, 7, 679935)),
        ),
    ]
