# Generated by Django 5.1.6 on 2025-04-11 11:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_alter_mealplan_created_at_alter_workout_created_at_and_more'),
        ('fitness', '0011_checkoutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 11, 16, 56, 10, 828174)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 11, 16, 56, 10, 828174), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 11, 16, 56, 10, 828174)),
        ),
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.signupdb')),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
