# Generated by Django 5.2 on 2025-04-16 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_rename_favoriteproduct_favoritesong_and_more'),
        ('fitness', '0012_alter_signupdb_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritesong',
            old_name='song',
            new_name='prod',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 12, 15, 56, 290194)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 16, 12, 15, 56, 281744), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 12, 15, 56, 290194)),
        ),
        migrations.AlterUniqueTogether(
            name='favoritesong',
            unique_together={('user', 'prod')},
        ),
    ]
