# Generated by Django 5.2 on 2025-04-16 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_rename_song_favoritesong_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 12, 23, 33, 268019)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 16, 12, 23, 33, 268019), null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 12, 23, 33, 268019)),
        ),
    ]
