# Generated by Django 5.1.6 on 2025-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Current_weight', models.IntegerField(blank=True, null=True)),
                ('Desired_weight', models.IntegerField(blank=True, null=True)),
                ('Height', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
