# Generated by Django 5.1.6 on 2025-02-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_contactdb_rename_class_classdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='email',
            new_name='Email',
        ),
    ]
