# Generated by Django 5.1.6 on 2025-03-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
