# Generated by Django 5.1.6 on 2025-03-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_remove_chat_created_at_chat_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
