# Generated by Django 5.2 on 2025-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_alter_signupdb_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='User_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
